web3ui/web3uikit

src/index.ts
added export declaration to make Tags usable in the frontend
=> fix: export Tag

src/styles/colors.ts
You can get the percentage of a color now like this
First Input takes a color in HEX. Best case a color we already have! 
Second takes percentage either as string or as a number 
`background: ${colorPercentage(colors.blueDark2, 20)}`
=> feat: get percentage by color

src/components/Info/Information.stories.tsx, src/components/Info/Information.styles.ts, src/components/Info/Information.test.tsx, src/components/Info/Information.tsx, src/components/Info/types.ts
Added this component from figma to repo. 
Customizable:
- title/topic
- information/description
=> feat(Information): added info card

src/components/BannerStrip/BannerStrip.styles.ts, src/components/Breadcrumbs/Breadcrumbs.styles.ts, src/components/Input/Input.styles.ts, src/components/Notification/Notification.styles.tsx, src/components/Radios/Radios.styles.ts, src/components/Tag/Tag.styles.ts, src/components/Tooltip/Tooltip.styles.ts
finally we now use all CSS and no strings =]
=> fix(css): styled components for remaining CSS props

src/components/Button/Button.test.tsx, src/components/Icon/Icon.test.tsx, src/components/NewComp/NewComp.stories.tsx, src/components/NewComp/NewComp.styles.ts, src/components/NewComp/NewComp.test.tsx, src/components/NewComp/NewComp.tsx, src/components/NewComp/index.tsx, src/components/NewComp/types.ts
this is a demo component for the community to clone and build on. if you see any of our agreements missing please call me up on it
=> Feat new comp demo

src/components/Input/Input.stories.tsx, src/components/Input/Input.styles.ts, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/types.ts
- added validation on inputs when user clicks away
- cleaned up Storybook to reduce the number of stories
- clean up the tests to reduce them
- added validation tests
- changed markup to new standard agreements
=> feat(Input): validation, better Stories, better tests

package.json
- now `yarn prettier`  runs automatically on commits
- added .json to list of prettier controlled files
=> Running prettier on commits

src/components/Card/Card.stories.tsx, src/components/Select/Select.stories.tsx
=> fix(Card/Select): remove the word server from web3uiKit

src/components/CryptoCards/CryptoCards.styles.tsx, src/components/CryptoCards/CryptoCards.tsx
=> fix(cryptocards):markup alignment

.gitignore, src/components/Checkbox/types.ts, src/components/Radios/types.tsx
Fixing issue https://github.com/web3ui/web3uikit/issues/64
=> fix(Checkbox,Radios): validation types naming convention (fixes #64)

src/components/Button/Button.styles.ts, src/components/Button/Button.tsx, src/components/Button/types.ts, src/components/Form/Form.stories.tsx, src/components/Form/Form.styles.ts, src/components/Form/Form.tsx, src/components/Form/types.ts
- added full width button
- added form to use button props as config
- added border radius to form
- minor padding and alignment fixes
=> fix(Form): Button to use its props interface in Form

src/components/Breadcrumbs/Breadcrumbs.stories.tsx, src/components/Breadcrumbs/Breadcrumbs.styles.ts, src/components/Breadcrumbs/Breadcrumbs.tsx
<Breadcrumbs> component:
- Refactored the styling
- Integrated the react-router-dom directly to the breadcrumbs
- Added a router wrapper for correct displaying in stories
=> refactoring: styling+router link added

package.json
=> chore version 0.1.22

src/components/CryptoCards/CryptoCards.stories.tsx, src/components/CryptoCards/CryptoCards.styles.tsx, src/components/CryptoCards/CryptoCards.tsx
- fixed CSS position issue cause Storybook demo to fold up
- removed alert from storybook and used click event
- various CONTRIBUTE alignments
=> fix(CryptoCards): CSS position issue, other minor fixes

.github/workflows/publish.yml, package.json, src/components/ConnectButton/ConnectButton.tsx
Added dynamic alpha/beta version deployment:
1. Press "Draft a new release"
2. Create a new tag (example: `0.1.26-beta.0`)
3. Check "pre-release" when adding a new release
1. Press "Draft a new release"
2. Create a new tag (example: `0.1.26`)
=> Feat/dynamic  publish

src/components/Button/Button.styles.ts, src/components/Button/Button.tsx, src/components/Button/styles/inititalStyles.ts, src/components/Button/types.ts, src/components/Loading/Loading.tsx, src/components/Loading/types.ts
- some minor fixes for Loading component
- added isLoading mode to Button
=> Feat button is loading mode

src/components/CreditCard/CreditCard.tsx
=> Chore: Typings

src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.styles.ts, src/components/Tag/Tag.tsx, src/components/Tag/styles/colors.tsx, src/components/Tag/styles/themes.tsx, src/components/Tag/types.ts
- increased accessibility
- aligned the code a little with the kit
- added missing stories for dark mode
=> feat(Tag): accessibility, alignment, stories

src/components/Avatar/Avatar.styles.tsx, src/components/Avatar/Avatar.test.tsx, src/components/Avatar/Avatar.tsx, src/components/Avatar/images/guy.tsx, src/components/Avatar/types.ts
- increased accessibility
- aligned the code a little with the kit
- custom images are now fully responsive
- fixed tests
=> feat(Avatar): Accessibility, alignment, responsive custom image

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/types.ts
made "ok"/"confirm" button color customizable.
added more stories for modal.
=> fix(modal): button + stories

src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/types.ts, yarn.lock
- added switchable text prop `labelWhenChecked` needed for Admin
- added new test
- added logic need
- added Story
=> feat(Checkbox): added switchable text

src/components/DatePicker/DatePicker.tsx, src/components/DatePicker/types.ts
=> fix(DatePicker): now return its change event and Date

src/components/Checkbox/Checkbox.tsx
=> fix(Checkbox): removed unwanted SVG in Switch mode

src/components/CopyButton/CopyButton.styles.ts, src/components/CopyButton/CopyButton.tsx, src/components/CopyButton/index.tsx, src/components/CopyButton/types.ts, src/components/Input/Input.styles.ts, src/components/Input/Input.tsx, src/components/Typography/Typography.stories.tsx, src/components/Typography/Typography.styles.ts, src/components/Typography/Typography.tsx, src/components/Typography/index.tsx, src/components/Typography/types.ts, src/index.ts
`<Typography copyable>` allows to copy content of the component
=> feat(Typography): copyable prop added

src/components/CreditCard/CreditCard.tsx
Ui and onPress/pressed improvements
=> feat(creditcard): onPress

src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Button/types.ts, src/components/Loading/Loading.tsx
Fix for centering loading on buttons. Also added loading props to allow users to override specific styles if necessary such as Spinner color.
=> feat: added cenetering for loading, and custom loading props, and stories

src/components/Dropdown/Dropdown.styles.tsx
z:index to 999 so overlay always shows up at the top
=> feat: Added 999 z index to dropdown tooltip so it shows up at the top

src/components/Card/Card.styles.ts, src/components/Card/Card.tsx, src/components/Card/types.ts
- added prop `cursorType`
- added hover transition animation
- fixed position of tooltip and selected icons
=> feat: better card styling added

src/components/Typography/Typography.stories.tsx, src/components/Typography/Typography.tsx, src/components/Typography/types.ts
A call back for when typography is copied
=> feat:call back for when typography is copied

src/components/CreditCard/CreditCard.tsx, src/components/Radios/Radios.stories.tsx, src/components/Radios/Radios.tsx, src/components/Radios/types.tsx
=> fix(Radios): unclickable radios

src/components/Notification/Notification.styles.tsx
So Notifcations pop up at the top
=> feat: notification to pop up at the top

src/components/CopyButton/CopyButton.test.tsx, src/components/CopyButton/CopyButton.tsx
Added tests for `CopyButton` component
=> feat: Add tests for CopyButton

src/components/Card/Card.styles.ts
removed design inconsistencies
P.S. We use `outline` here instead of `border` because of gradient background which works not correctly with transparent border
=> upd: Card styling

src/components/Card/Card.styles.ts, src/components/Card/Card.tsx
=> fixed(Card): style

src/components/BannerStrip/BannerStrip.stories.tsx, src/components/BannerStrip/BannerStrip.tsx, src/components/BannerStrip/types.ts
BREAKING CHANGES:
replaced button props with buttonConfigProp to have more control over button within BannerStrip
=> Breaking Change: BannerStrip buttonConfig + height

src/components/Checkbox/Checkbox.styles.ts, yarn.lock
- added curser pointer
- yarn updated Storybook's dependancies
=> fix: checked cursor and yarn lock update

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.styles.ts, src/components/Modal/Modal.tsx, src/components/Modal/types.ts
- Modals now do not exceed 96vh
- if too big the become scrollable
- new width prop that will take any string 
- naming conventions fix
- Storybook docs fixed for positioning
- new Stories added for height and width
- some minor responsive tweaks
=> feat(Modal): 202 scrollable, 192 width

src/components/CopyButton/CopyButton.styles.ts
Adding this to avoid this issue
e
=> feat: add copy Icon max Widths

src/components/Badge/Badge.stories.tsx, src/components/Badge/Badge.styles.ts, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx, src/components/Badge/index.tsx, src/components/Badge/types.ts, src/index.ts, yarn.lock
Things done in this PR:
1. Added Badge component with 3 props - text, state, textVariant (textVariant takes all values-h1,h2...etc that typography component can use)
2. Create stories for the component.
3. Written simple tests for the badge component.
Please find below screenshot of all the badges.
Please let me know your suggestions. 😄
=> [Feat]: Add Badge Component

src/components/Stepper/Stepper.stories.tsx, src/components/Stepper/Stepper.styles.ts, src/components/Stepper/Stepper.tsx, src/components/Stepper/types.ts
=> feat: stepper header can now be aligned manually

src/components/Modal/Modal.tsx, src/components/Modal/types.ts
=> feat:modal title to jsx element

src/components/Dropdown/Dropdown.styles.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/types.ts
- added prop for disabling outline
- updated style to match UI design
- old text replaced by Typography component
- added prop `defaultOptionIndex`
=> feat(Dropdown): more stylings added

src/components/Avatar/Avatar.stories.tsx, src/components/Avatar/Avatar.styles.tsx, src/components/Avatar/Avatar.test.tsx, src/components/Avatar/Avatar.tsx, src/components/Avatar/types.ts
=> feat: avatar features, bgCOlor, and border Radius

src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/Skeleton.styles.ts, src/components/Skeleton/Skeleton.test.tsx, src/components/Skeleton/Skeleton.tsx, src/components/Skeleton/index.tsx, src/components/Skeleton/types.ts, src/index.ts, src/styles/colors.ts
Added Skeleton component.
Close #219 
https://user-images.githubusercontent.com/35369843/157483491-884fdc5b-2712-4a6c-acd6-9127d906e9fd.mp4
Let me know if any changes are required in this.
=> Add Skeleton Component

src/components/Stepper/Stepper.tsx
making an easy way for people to overwrite our styles if they know the basics ;)
=> feat(Stepper): dynamic CSS IDs overwrite options

src/components/Form/Form.stories.tsx, src/components/Form/Form.styles.ts, src/components/Form/Form.tsx, src/components/Form/types.ts
=> feat: added footer feature for form

src/components/Tag/Tag.styles.ts, src/components/Tag/Tag.tsx, src/components/Tag/styles/themes.tsx, src/components/Tag/types.ts
- in discount mode width = height and 50% border radius = perfect circle
- added font size to we can make big ass text
=> feat(Tag): buffed discount mode options

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.styles.ts, src/components/Modal/Modal.tsx
=> fix: modal button position when title is undefined

src/components/ConnectButton/ConnectButton.tsx, src/components/WalletModal/WalletModal.tsx, src/components/WalletModal/types.ts
=> feat: added moralisAuth prop to walletmodal

src/components/Dropdown/Dropdown.stories.tsx, src/components/Dropdown/Dropdown.styles.tsx, src/components/Dropdown/Dropdown.tsx
=> Revert "fix: dropdown item overflow and font weight"

src/components/Button/Button.tsx
=> bugfix: fixing loading

src/components/Form/Form.stories.tsx, src/components/Form/Form.tsx, src/components/Form/types.ts, src/components/Radios/Radios.styles.ts, src/components/Radios/Radios.tsx, src/components/Radios/types.tsx
Add Disable state to form component
=> Add Disable State to all form components

src/Widget/Widget.stories.tsx, src/Widget/Widget.styles.ts, src/Widget/Widget.test.tsx, src/Widget/Widget.tsx, src/Widget/types.ts, src/styles/fonts.ts
Added Widget component
- topic
- title
- children (optional) will be populated to the right side
=> feat(Widget): init

src/components/Table/Table.styles.ts, src/components/Table/Table.tsx, src/components/Table/types.tsx
https://user-images.githubusercontent.com/62478924/158871854-b46769ba-603e-4632-92ca-e3b709111005.mov
=> Add Align Items in Table Cell Components

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.styles.ts, src/components/Modal/Modal.tsx, src/components/Modal/types.ts
Fix warning nested div in Modal component. <br />
=> fix: nested close buttons Modal component

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.styles.ts, src/components/Modal/Modal.tsx, src/components/Modal/types.ts
=> feat: custom overflow rule Modal component

src/components/Stepper/Stepper.stories.tsx, src/components/Stepper/Stepper.styles.ts, src/components/Stepper/types.ts
=> feat: allow ReactNode element as final message in Stepper component

src/components/Icon/collection.tsx, src/components/Icon/icons/metamask.tsx
Metamask icon added
`<Icon svg='metamask' />`
=> feat: metamask icon added

src/components/CopyButton/CopyButton.stories.tsx, src/components/CopyButton/CopyButton.styles.ts, src/components/CopyButton/CopyButton.tsx
=> Fix: copyButton height and centered position

src/components/Button/Button.styles.ts, src/components/Button/Button.test.tsx, src/components/Button/styles/inititalStyles.ts, src/components/Button/styles/sizeStyles.ts, src/components/Button/styles/standardThemes.ts, src/styles/colors.ts
Update of Button styles after changes in Figma Designs
=> fix(Button): mismatches in design and styles

src/components/Notification/Notification.tsx, src/components/Notification/types.ts
closes #312 
you are now able to pass in colors for the icon - if not set color will be grey
=> fix(Notification): icon-color

src/components/Notification/types.ts
=> fix: add iconColor to PayloadType

src/components/Blockie/Blockie.stories.tsx, src/components/Blockie/Blockie.tsx, src/components/Blockie/types.ts, src/components/ConnectButton/ConnectButton.tsx
Removed required Moralis for Blockie component
=> feat: Blockie no moralis needed

src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx
- values are now dynamic so look better in Storybook but also work with async values
- added a story to explain the filled hack for placeholders and any other UI situations
=> feat(Input): dynamic value and filled hack story

src/components/Hero/Hero.stories.tsx, src/components/Hero/Hero.styles.ts, src/components/Hero/Hero.tsx, src/components/Hero/types.ts
This PR is a solution to this [issue](https://github.com/web3ui/web3uikit/issues/328) 
I've added to custom props
1. rounded - to give an hero a curved border
2. align - to set the position of the hero content
also i created an example in the story section which is an attempt for me to implement Dapp hero section (check the attached screenshot).
=> completed the refactor of hero component

src/components/Input/Input.tsx
=> fix(Input): removing bad value fix

src/components/Input/Input.tsx, src/components/Input/types.ts
Standard Input "autoFocus" prop added
=> feat: input autofocus added

src/components/Tooltip/Tooltip.styles.ts, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/types.ts
=> feat: add min width to tooltip

src/components/NFTCollection/NFTCard.tsx, src/components/NFTCollection/NFTCollection.styles.ts, src/components/NFTCollection/NFTCollection.tsx
- made the images more responsive
- added accessibility so users still know they are images
- added some display name tags to help debugging
- moved some markup around to make maintenance a little easier
=> fix(NFTCollection): minor fix for more responsive images

src/components/Hero/Hero.stories.tsx, src/components/Hero/Hero.styles.ts, src/components/Hero/Hero.tsx, src/components/Hero/types.ts
This is a request to fix [this](https://github.com/web3ui/web3uikit/issues/338)
=> fix for hero

README.md
- Fixed all stories links
- I used only the component page without the properties so the link will always redirect to the default state
=> Fix readme incorrect links

src/components/Tag/Tag.styles.ts, src/components/Tag/Tag.tsx, src/components/Tag/styles/colors.tsx, src/components/Tag/styles/themes.tsx, src/components/Tag/types.ts, src/components/Todo/Todo.stories.tsx, src/components/Todo/Todo.styles.ts, src/components/Todo/Todo.test.tsx, src/components/Todo/Todo.tsx, src/components/Todo/index.tsx, src/components/Todo/types.ts, src/styles/colors.ts
A pr to solve this [issue](https://github.com/web3ui/web3uikit/issues/343)
=> 343 todo list component needed

README.md, src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.styles.ts, src/components/Accordion/Accordion.test.tsx, src/components/Accordion/Accordion.tsx
- hasIcon story is fixed
- naming standardised
=> 355 react refactor accordion

src/components/ChainSelector/index.ts, src/index.ts
We did not export the chain selector component.
=> fix: export chain selector component

README.md, src/components/Badge/Badge.styles.ts, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx
- added description in readme
closes #358
=> React18 refactor Badge

src/components/Form/Form.styles.ts, src/components/Form/Form.test.tsx, src/components/Form/Form.tsx
- checked all layouts / setups are rendered in stories
=> fix(Form): refactored tests and styles import/export

src/components/ConnectButton/ConnectButton.tsx, src/components/ConnectButton/connectors.ts, src/components/ConnectButton/types.ts, src/components/WalletModal/WalletModal.tsx, src/components/WalletModal/config.ts, src/components/WalletModal/types.ts, src/decorators.tsx
added the signingMessage props, so as to enable custom message to the <Connectbutton />
=> add signingMessage to ConnectButton

src/components/LinkTo/LinkTo.styles.ts, src/components/LinkTo/LinkTo.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.styles.ts
Modal button fix
Modal width fix
LinkTo long text fix
=> 400 linkto and modal more responsive

src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.styles.ts, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/types.ts
A fix to this **[issue](https://github.com/web3ui/web3uikit/issues/388)**
=> tool tip refactor

src/components/Hero/Hero.tsx, src/components/Hero/types.ts
background URL should not be required prop
=> fix: typing in Hero Component

src/components/Button/styles/coloredThemes.ts, src/components/Button/styles/standardThemes.ts, src/components/ConnectButton/ConnectButton.stories.tsx, src/components/NFTCollection/NFTCollection.stories.tsx, src/components/Todo/Todo.stories.tsx, src/components/Todo/Todo.styles.ts, src/components/Todo/Todo.tsx, src/components/Todo/types.ts, src/components/WalletModal/WalletModal.stories.tsx, src/components/WalletModal/WalletModal.styles.ts
- feat(Button): improved accessibility with focus styles
- fix(ConnectButton): made storybook docs better with decorator
- feat(WalletModal): fix storybook with decorator and made responsive
=> Feat todo and various fixes

src/components/Checkbox/Checkbox.styles.ts, src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx
=> React18 test refactor Checkbox

src/components/Card/Card.styles.ts, src/components/Card/Card.test.tsx, src/components/Card/Card.tsx
=> React18 refactor Card

src/components/CryptoCards/CryptoCards.styles.tsx, src/components/CryptoCards/CryptoCards.test.tsx, src/components/CryptoCards/CryptoCards.tsx, src/components/CryptoCards/types.ts
=> React18 refactor Cryto Cards

src/components/TextArea/TextArea.styles.ts, src/components/TextArea/TextArea.test.tsx, src/components/TextArea/TextArea.tsx
A fix for this **[issue](https://github.com/web3ui/web3uikit/issues/386)**
=> 386 react refactor textarea

src/components/Tag/Tag.styles.ts, src/components/Tag/Tag.tsx, src/components/Tag/styles/themes.tsx, src/components/Tag/types.ts
=> Added new tag theme: "broader"

src/components/HideButton/HideButton.test.tsx
tests meet React18 standards
all layouts / setups are rendered in stories
closes #368
=> React18 refactor HideButton

src/components/ChainSelector/ChainSelector.test.tsx, src/components/ChainSelector/ChainSelector.tsx
Refer to issue #406 
Added functionality to toggle into deselect all once all the cards are selected and vice versa
=> feat: Chain selector deselect

src/components/Radios/Radios.cc.stories.tsx, src/components/Radios/Radios.stories.tsx, src/components/Radios/Radios.styles.ts, src/components/Radios/Radios.test.tsx, src/components/Radios/Radios.tsx, src/components/Radios/types.tsx
A fix for this **[issue](https://github.com/web3ui/web3uikit/issues/380)**
=> 380 react refactor radios

src/components/Info/Information.styles.ts, src/components/Info/Information.test.tsx, src/components/Info/Information.tsx
=> React18 refactor information

src/components/Notification/Notification.test.tsx, src/components/Notification/NotificationProvider.tsx
Fixes tests and react 18 implicit children
Closes #377 #437
=> fix(Notification): react 18

src/components/Row/Row.styles.ts, src/components/Row/Row.test.tsx, src/components/Row/Row.tsx
A solution to this **[issue](https://github.com/web3ui/web3uikit/issues/381)**
=> 381 react18 refactor row

src/components/PopoverDropdown/PopoverDropdown.styles.tsx, src/components/PopoverDropdown/PopoverDropdown.test.tsx, src/components/PopoverDropdown/PopoverDropdown.tsx, src/components/PopoverDropdown/types.ts, src/components/PopoverElement/PopoverElement.styles.tsx, src/components/PopoverElement/PopoverElement.test.tsx, src/components/PopoverElement/PopoverElement.tsx, src/components/Stepper/Stepper.styles.ts, src/components/Stepper/Stepper.test.tsx, src/components/Stepper/Stepper.tsx
Closes #384 
Closes #378 
Closes #379
=> fix(react18): tests, styles, children

README.md, src/components/LinkTo/LinkTo.stories.tsx, src/components/LinkTo/LinkTo.test.tsx
- scoped CSS without named exports checked
=> feat: React18 refactor LinkTo

README.md, src/components/Logo/Logo.stories.tsx, src/components/Logo/Logo.test.tsx
- diners story is fixed
- amex story is fixed
=> feat: React18 refactor Logo

README.md, src/components/Modal/Modal.styles.ts, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx
=> feat: React18 Refactor Modal

src/components/NewComp/NewComp.styles.ts, src/components/NewComp/NewComp.test.tsx, src/components/NewComp/NewComp.tsx
=> feat: NewComp React18 Refactor

src/components/NFTCollection/NFTCollection.test.tsx
=> fix(NFTCollection) test

src/components/Select/Select.stories.tsx, src/components/Select/Select.styles.ts, src/components/Select/Select.tsx, src/components/Select/index.tsx, src/components/Skeleton/Skeleton.test.tsx
A fix for this **[issue](https://github.com/web3ui/web3uikit/issues/383)**
=> 383 react18 refactor skeleton

README.md, src/components/NFT/NFT.stories.tsx, src/components/NFTBalance/NFTBalance.stories.tsx
Fixed docs in storybook and added components in the readme. (For readme file could not find any address with moralis NFT)
Let me if description is readme file is ok or should i add/remove anything.
Closes #451
=> Add docs for NFT components

src/components/LinkTo/LinkTo.stories.tsx, src/components/LinkTo/LinkTo.styles.ts, src/components/LinkTo/LinkTo.test.tsx, src/components/LinkTo/LinkTo.tsx, src/components/LinkTo/types.ts
- Added internal to type prop
- Using Link(from react-router)
- Added a new story
- Added a test for this new story
=> Add Internal Type to LinkTo Component

src/components/NewComp/NewComp.styles.ts, src/components/NewComp/NewComp.tsx, src/components/NewComp/types.ts, src/interfaces/color.ts
- Added an interface for colors.
- Added an optional type(bgColor) in NewComp to show how to use this component. (This might help others know how to use this type. Let me know if this needs to removed)
closes #74
=> Add Color Interface

src/components/Radios/Radios.styles.ts, src/components/Radios/Radios.tsx, src/components/Radios/types.tsx
Things done.
- Added isRow optional prop. default set to false.
- Added styles for the functionality
- Sort lines in CSS
closes #465 
Small screen
Large Screen
=> feat: Add isRow prop to radio button

README.md, src/components/CodeArea/CodeArea.styles.tsx, src/components/CodeArea/CodeArea.test.tsx, src/components/CodeArea/CodeArea.tsx, src/components/CodeArea/LineNumbers.tsx
Works correctly on firefox browser now
closes #452
=> fix: oneline textarea bug

src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.styles.ts, src/components/Modal/Modal.tsx
- Fixed the color override issue (while using typography component).
- Changed the Cancel button in Footer - changed text color to grey and black on hover
- Added border to Close button in header to match the design
closes #462
=> fix: Modal header and close button styles

src/components/Input/Input.styles.ts, src/components/Input/Input.tsx, src/components/Input/types.ts
Added icon prefix type for inputs
Added ability to change input into, this allows for injecting refs from client side code
=> feat: add input prefix for input icons

src/components/Form/Form.tsx, src/components/Stepper/Stepper.test.tsx
- fix Stepper as it has unused import and const
- fix Form to disable the submit button onSubmit
=> 484 form after submit

src/components/Button/Button.test.tsx, src/components/Button/styles/sizeStyles.ts
Updated font sizes and paddings for buttons following to the designs
closes #493
=> fix: button sizes

src/components/DatePicker/DatePicker.tsx, src/components/Input/Input.styles.ts, src/components/Input/Input.tsx, src/components/Input/types.ts
=> feat: added description component

src/components/Stepper/Stepper.styles.ts
=> Fix stepper space

src/components/Icon/collection.tsx, src/components/Icon/icons/google.tsx
**Have zoomed in this image for better visibility
closes #506
=> feat: add google icon

src/components/Select/Select.stories.tsx, src/components/Select/Select.styles.ts, src/components/Select/Select.tsx, src/components/Select/types.ts
Add prefix icon #520 
https://user-images.githubusercontent.com/13832392/165855399-f42dd7e5-4802-4201-854c-23aec40ec383.mp4
=> Add prefix icon to select component

src/components/Button/styles/inititalStyles.ts, src/components/Table/MockData.tsx, src/components/Table/Table.stories.tsx, src/components/Table/Table.styles.ts, src/components/Table/Table.tsx
1. closes #508
2. fixed transparent button issue
3. sync table example, etc
=> 508 table outdated style

src/components/PaymentCard/PaymentCard.stories.tsx, src/components/PaymentCard/PlanCard.stories.tsx, src/components/PaymentCard/PlanCard.styles.tsx, src/components/PaymentCard/PlanCard.test.tsx, src/components/PaymentCard/PlanCard.tsx, src/components/PaymentCard/mock.tsx, src/components/PaymentCard/types.ts
=> 477 pricing plan card does not much designs

src/components/PaymentCard/Components/YourPlanButton/YourPlanButton.styles.tsx, src/components/PaymentCard/Components/YourPlanButton/index.tsx, src/components/PaymentCard/PlanCard.stories.tsx, src/components/PaymentCard/PlanCard.styles.tsx, src/components/PaymentCard/PlanCard.test.tsx, src/components/PaymentCard/PlanCard.tsx, src/components/PaymentCard/types.ts
=> 477 pricing plan card your plan toggle

src/components/Widget/Widget.stories.tsx, src/components/Widget/Widget.tsx, src/components/Widget/types.ts
adding is loading state to widgets
=> feat(Widget) isLoading state

src/components/Button/Button.stories.tsx, src/components/Button/styles/standardThemes.ts
=> removed extra padding and border on active outlineLarge button

src/components/ChainSelector/ChainSelector.tsx
=> fix: IsMultipleAllowed with isCompatibilityChecked bug

src/components/Button/Button.stories.tsx, src/components/Button/Button.styles.ts, src/components/Button/Button.test.tsx, src/components/Button/styles/coloredThemes.ts, src/components/Button/styles/inititalStyles.ts, src/components/Button/styles/standardThemes.ts, src/components/Button/types.ts, src/styles/colors.ts
1. closes #505 
2. warning button 
3. success button
4. error button
5. ghost button
6. link button
7. text button
=> button updates

src/components/Checkbox/Checkbox.styles.ts
- Changed font size.
- Changed font colour.
=> Fix: Change fonst-size and color to match design.

src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/types.ts, src/components/Input/Input.stories.tsx, src/components/Input/Input.test.tsx, src/components/Input/Input.tsx, src/components/Input/types.ts, src/components/Radios/Radios.cc.stories.tsx, src/components/Radios/Radios.stories.tsx, src/components/Radios/Radios.tsx, src/components/Radios/types.tsx, src/components/Select/Select.tsx, src/components/Select/types.ts, src/components/TextArea/TextArea.stories.tsx, src/components/TextArea/TextArea.tsx, src/components/TextArea/types.tsx
Implemented
- onBlur functionality added to the input component 
- Added the function to input storybook
- added ref to the input component
- added the necessary types 
- added test for onBlur function.
After Review
- implement the same for select, radios, textarea, and checkbox
=> 546 input onblur ref props

src/components/PlanCard/PlanCard.styles.tsx
- Set box-sizing to border-box.
=> Fix: Set box sizing to border-box to include padding in width.

src/components/Credentials/components/TruncateString.tsx
=> fix: credentials comp rerender on prop update

src/components/Dropdown/Dropdown.test.tsx, src/components/Dropdown/Dropdown.tsx, src/components/Dropdown/types.ts
New prop - dropdownArrowType
values - normal | filled
case1 - Normal (default) 
case2 - Filled 
closes #567
=> [Dropdown] : add dropdown filled arrow

src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/types.ts
=> 568 checkbox does not couple state with props which can cause potential memory leaks + JSX element label

src/components/Hero/Hero.styles.ts
A fix to reduce hero fonts on smaller device
=> hero font size for smaller devices

src/components/Credentials/Credentials.styles.tsx
=> responsiveness fix for credentials 

src/components/Stepper/Stepper.styles.ts
=> feat: fix loading spinner

src/components/Button/Button.styles.ts
While in console mode on dev tools a table keeps get logged making difficult to find the console.log information from progra
m
=> Commented out table logging

src/components/VerifyCode/VerifyCode.styles.ts, src/components/VerifyCode/VerifyCode.tsx
https://user-images.githubusercontent.com/60792849/169143993-517c32fe-5b23-4b1c-a5d7-54784e87826c.mov
=> 598 verifycode should not allow two digits in one input

src/components/Notification/Notification.styles.tsx
=> fix(Notification): jumping text

src/components/Checkbox/Checkbox.tsx, src/components/Checkbox/types.ts
=> fix: checkbox state&rerender

src/components/Todo/Todo.tsx
removed red(error) color from todo
=> removed red(error) color from todo

src/components/Loading/Loading.styles.tsx, src/components/Loading/Loading.tsx
---
---
Related issue: Loco wanted CSS power
CSS is still king baby!
=> make loading faster

src/components/Todo/Todo.tsx
---
name: Unique Todo Items
about: This PR prevents double entries on todo IP items
---
add all input items into a set and then convert it into an array
=> made todo item unique

src/components/VerifyCode/VerifyCode.stories.tsx, src/components/VerifyCode/VerifyCode.styles.ts, src/components/VerifyCode/VerifyCode.tsx, src/components/VerifyCode/types.ts
---
name: 'Verify Code'
about: add Error Message
---
Add error message and also fix bug which lets user input - [e,E,+,-,.]
Related issue: #612 
Added state and errorMessage prop
Add code onKeyDown to restrict the inputs
=> feat: Error message for verify code

src/components/Table/Helper.ts, src/components/Table/MockData.tsx, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/types.tsx
---
name: 'Table Component'
about: Sorting columns
---
Related issue: #610 
Added a prop that would take boolean array input. True if column is sortable else false.
On clicking on appropriate table header the table would be sorted.
Please checkout Table-> Sync Table example story
=> feat: add sorting columns for table

src/components/WalletModal/WalletModal.tsx
=> feat: error message non ethereum browser

src/components/CryptoLogos/CryptoLogos.stories.tsx, src/components/Illustrations/images/chains/cronos.tsx
=> add cronos story and fix size

.github/workflows/chromatic.yml, package.json, yarn.lock
=> feat: chromatic

src/components/Typography/Typography.stories.tsx, src/components/Typography/Typography.tsx
=> fix(Typography): docs and minor alignments

src/components/Input/Input.styles.ts, src/components/Input/Input.tsx, src/components/Radios/Radios.styles.ts
---
name: 'Input and Radio Comp'
about: Bug Fixes
---
Related issue: #651  #633 and Radio Text Size Bug
651 - maxCharacterLength is checked on all input types now
653 - if placeholder is given its now visible and label position changes
Saw that radio button text size is increased (Not sure how 🤔 ). Have commented out the code incase it is a required feature. 
Also changed the filled input color to BlueSky to match the design file 
These were small changes so did them in a single PR hope that is ok 😋
=> Input and Radio Bug Fixes

src/components/Modal/Modal.styles.ts
---
about: Modal styling tweaks
---
Related issue: #665
=> style(Modal): overlay color and title padding

src/components/Todo/Todo.tsx
With No Regex
https://user-images.githubusercontent.com/62478924/175357894-046305dc-ffac-49d2-b934-c619786a1a68.mp4
With Regex
http://www.giphy.com/gifs/CqMwWbfQQlZl1Wz79e
=> 668 Refactor Todo component to remove dependency on Form

src/components/Table/Table.stories.tsx, src/components/Table/Table.test.tsx, src/components/Table/Table.tsx, src/components/Table/types.tsx
http://www.giphy.com/gifs/UpnASvs9DfBbJf836y
Added Row Click prop to Table Component
=> Feature: Table Row Click

src/components/Form/Form.tsx
Signed-off-by: Jules Claussen <jules.claussen@valiantys.com>
---
about: Fix title for Form component
---
Related issue: #670 
Simply edited one line to display the title as the $name, and not the $value.
=> Fix title of textArea in <Form /> component

src/components/PopoverDropdown/PopoverDropdown.stories.tsx, src/components/PopoverDropdown/PopoverDropdown.styles.tsx, src/components/PopoverDropdown/PopoverDropdown.test.tsx, src/components/PopoverDropdown/PopoverDropdown.tsx, src/components/PopoverDropdown/index.tsx, src/components/PopoverDropdown/types.ts, src/utils/depreciationWarning.ts
---
name: 'Popover Dropdown with CSS and less JS'
about: no breaking changes but now CSS powered, also depreciation warning function added
---
Related issue: https://github.com/web3ui/web3uikit/issues/648
- stripped JS and used more performant CSS
- remove move and moveBody props as we do not need them now
- added depreciation warning util
=> 648 rebuild dropdown

src/components/Todo/Todo.tsx
---
name: 'Todo component remove require'
---
=> 678 todo component should input not have required input

src/components/LinkTo/LinkTo.stories.tsx, src/components/LinkTo/LinkTo.styles.ts, src/components/LinkTo/LinkTo.test.tsx, src/components/LinkTo/LinkTo.tsx, src/components/LinkTo/types.ts
---
about: LinkTo component
---
Related issue: #661 
Added a 'none' iconLayout prop value to hide the icon. Also fixed the alignment.
@BillyG83 i know we feature freezing web3uikit but this is a small feature and would be useful to many users.
Anyway i have this added in monorepo so it's good to have it here too.
=> LinkTo: add optional icon feature

CONTRIBUTE.md
Signed-off-by: Jande Vincent
email: janvinsha@gmail.com
---
name: 'docs:correct installation of yarn in contribute.md'
about: correct installation of yarn in contribute.md, related to issue #691
---
Related issue: #`691`
The solution was to edit the docs to `yarn install`
=> docs:correct installation of yarn in contribute.md

src/components/Checkbox/Checkbox.styles.ts, src/components/Upload/Upload.test.tsx, src/components/Upload/Upload.tsx, src/components/Upload/types.ts
---
name: Checkbox alignment fix
about: Dani eagle eye spotted a minor alignment issue with checkbox 
---
Checkbox should be aligned-centre with the box
Related issue: #686
- Checkbox is center aligned with it text now
- The hidden input is hidden top left of the element, this means when HTML5 validation of form spots an issue the screen will roll up to that exact place for the element
=> fix(Checkbox): box alignment and hidden input for validation prompt

src/components/ConnectButton/ConnectButton.tsx
---
name: 'feat:added ens support in connect button component'
about: Pr to fix issue #698 
---
Related issue: #698 
final image is below
=> feat:added ens support in connect button

src/components/PopoverDropdown/PopoverDropdown.styles.tsx, src/components/PopoverDropdown/PopoverDropdown.tsx
=> fix(PopoverDropdown): change move to movebody

.prettierrc, src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.styles.ts, src/components/Tabs/Tabs.test.tsx, src/components/Tabs/TabsList.tsx, src/components/Tabs/types.ts
---
about: Tablist
---
Related issue: #706, #722 
Added custom width for the tablist component.
Custom height can be achieved through the existing lineHeight prop on Tab comp.
Added a new story for this.
=> Fix: Tablist auto width and overflow

.prettierrc, src/components/ConnectButton/ConnectButton.tsx, src/components/ENSAvatar/ENSAvatar.stories.tsx, src/components/ENSAvatar/ENSAvatar.styles.ts, src/components/ENSAvatar/ENSAvatar.tsx, src/components/ENSAvatar/index.tsx, src/components/ENSAvatar/types.ts
---
about: ENS Avatar
---
Add address, and size prop to ENSAvatar.
Connect Button - use ENSAvatar instead of normal blockie
=> ENSAvatar: add size and address prop

.github/workflows/size.yml, .github/workflows/storybook.yml, package.json, packages/web3/package.json, pnpm-lock.yaml
=> fix: storybook yml file

.github/workflows/publish.yml
PR to test scoped publish job to build packages under one registry
=> Test, scoped npm build packages for mono repo

.changeset/config.json
=> chore(changeset): config file fix

packages/core/src/lib/ChainSelector/index.ts, packages/core/src/lib/Notification/index.tsx, packages/web3/src/lib/SendTransaction/SendTransaction.stories.tsx, packages/web3/src/lib/SendTransaction/SendTransaction.test.tsx, packages/web3/src/lib/SendTransaction/SendTransaction.tsx, packages/web3/src/lib/SendTransaction/example/VendingMachine.sol, packages/web3/src/lib/SendTransaction/example/contractData.ts, packages/web3/src/lib/SendTransaction/index.tsx, packages/web3/src/lib/SendTransaction/types.ts, packages/web3/src/lib/index.ts
---
---
Related issue: #605 
Send Transaction button - button to call a function on the contract
=> feat: Add send transaction button

apps/example/src/index.tsx, packages/web3/src/lib/ConnectButton/index.tsx, packages/web3/src/lib/WalletModal/types.ts
=> Updated PR

.changeset/config.json, .github/workflows/publish.yml, package.json, pnpm-lock.yaml
=> fix: release action and add Github changelog

.changeset/seven-mice-exercise.md, apps/example/src/index.tsx, packages/core/package.json, packages/core/vite.config.ts, pnpm-lock.yaml
=> [Breadcrumb]: Fix react router dom dependency issue

packages/core/src/lib/LinkTo/LinkTo.styles.ts
minor CSS fix that is causing a weird bug in Admin
=> fix(LinkTo): margin top auto removed

.changeset/config.json, .changeset/moody-camels-boil.md, .storybook/main.js, apps/example/package.json, apps/example/src/bootstrap.tsx, apps/example/src/index.tsx, package.json, packages/web3uikit/CHANGELOG.md, packages/web3uikit/package.json, packages/web3uikit/project.json, packages/web3uikit/src/index.ts, packages/web3uikit/tsconfig.json, packages/web3uikit/vite.config.ts, pnpm-lock.yaml
---
about: web3uikit
---
All packages core,web3,icons,styles exported together in web3uikit package.
=> [Feat]: web3uikit umbrella package

packages/core/src/lib/Notification/Notification.styles.tsx
---
---
Related issue: #785 
Small css change
=> [Fix]: Notification message newline not showing

.changeset/eighty-owls-nail.md
=> For release

.changeset/loud-ravens-press.md, packages/core/src/lib/Table/Table.tsx
---
---
Add this to stories locally to test
```jsx
const argsTest = {
columnsConfig,
header,
pageSize,
maxPages,
isColumnSortable: [false, true, false, false],
};
const TestTemplate: ComponentStory<typeof Table> = (args) => {
const [val, setVal] = React.useState(data);
return (
<div>
<button onClick={() => setVal(data.slice(1, 10))}>Click</button>
<Table data={val} {...argsTest} />
</div>
);
};
export const Test1 = TestTemplate.bind({});
```
=> [Table]: Search issue in admin

.changeset/slow-readers-live.md, .changeset/sour-beans-reflect.md, packages/core/src/lib/Select/Select.stories.tsx, packages/core/src/lib/Select/SelectBeta/SelectBeta.styles.ts, packages/core/src/lib/Select/SelectBeta/SelectBeta.tsx, packages/core/src/lib/Select/SelectBeta/components/SelectMenuList.tsx, packages/core/src/lib/Select/SelectBeta/components/SelectedItemsList.tsx, packages/core/src/lib/Select/types.ts
---
---
1. Fix no icon styles
2. Add height customization for both select box and select menu
=> [Fix]: Select styles and Add height customizations

.changeset/stupid-spoons-fold.md, packages/core/src/lib/Select/SelectBeta/SelectBeta.styles.ts, packages/core/src/lib/Select/SelectBeta/SelectBeta.test.tsx, packages/core/src/lib/Select/SelectBeta/SelectBeta.tsx, packages/core/src/lib/Select/SelectBeta/components/SelectMenuList.tsx
=> [Select Beta]: fix beta component styles

.changeset/neat-brooms-play.md, packages/core/src/lib/Stepper/Stepper.tsx
A small fix for Stepper, the final title is now an H2 so it matches the other titles
=> fix(Stepper): complete title is H2

.changeset/swift-pets-hear.md, apps/example/src/index.tsx, packages/core/src/lib/Button/ButtonBase/ButtonBase.tsx, packages/core/src/lib/Modal/Modal.tsx
---
---
Related issue: #775 
1. Fixes unique key warning from react in button and modal
2. Modal closeButton props implementation fixed.
=> [Button,Modal]: fix unique key warning in react

.changeset/gold-pens-rhyme.md, packages/core/src/lib/CodeArea/CodeArea.styles.tsx, packages/core/src/lib/CodeArea/LineNumbers.tsx, packages/core/src/lib/Credentials/components/CredentialsHeader.tsx, packages/core/src/lib/PopoverDropdown/PopoverDropdown.tsx
---
---
Issue : On maxized button click the code area goes behind all components instead of expanding its height.
After Fixing:
Also fixed some key warning in popover and credentials header
=> [Code Area]: Fix Component hidden on Maximized state

.changeset/beige-fireants-worry.md, packages/core/src/lib/Table/Table.stories.tsx, packages/core/src/lib/Table/Table.styles.ts, packages/core/src/lib/Table/Table.tsx, packages/core/src/lib/Table/types.tsx
=> [Table]: custom data on all pages

.changeset/green-panthers-perform.md, packages/core/src/lib/Stepper/Stepper.stories.tsx, packages/core/src/lib/Stepper/Stepper.tsx, packages/core/src/lib/Stepper/types.ts
=> Add event to next button

packages/core/src/lib/Table/Table.stories.tsx
---
---
New story with Custom Loading component
Related issue: #834 
I Added new Story in Table component named CustomLoadingSkeleton. Here I showed some skeletons of table rows using Skeleton component which is different than basic round Loader.
=> added new story in Table with custom loading Skeleton component

.changeset/beige-moles-glow.md, packages/core/src/lib/Input/Input.test.tsx, packages/core/src/lib/Slider/Slider.stories.tsx, packages/core/src/lib/Slider/Slider.styles.ts, packages/core/src/lib/Slider/Slider.test.tsx, packages/core/src/lib/Slider/Slider.tsx, packages/core/src/lib/Slider/index.tsx, packages/core/src/lib/Slider/types.ts, packages/core/src/lib/index.ts, packages/web3/src/lib/IPFSInput/IPFSInput.stories.tsx
---
---
Have added styles according to our admin panel requirements and made it flexible too
=> [Slider]: Slider component with new styles

.changeset/cool-gifts-fold.md, packages/core/src/lib/Button/ButtonColored/ButtonColored.styles.tsx
---
---
Related issue: [#848](https://github.com/web3ui/web3uikit/issues/848).
Fixed colored button overflow ([issue](https://github.com/web3ui/web3uikit/issues/848)) by adding `border-radius: 10px;` to `:after`.
=> fixed colored button overflow

.changeset/breezy-tables-allow.md, packages/core/src/lib/Table/Table.stories.tsx, packages/core/src/lib/Table/Table.styles.ts, packages/core/src/lib/Table/Table.tsx, packages/core/src/lib/Table/types.tsx, packages/icons/README.md
---
---
Related issue: [#845](https://github.com/web3ui/web3uikit/issues/845)
- Added `headerTextColor` and `headerBgColor` props to Table component
- Updated link in README.md for icons docs (gallery)
=> [Table]: added color props

.changeset/angry-pandas-change.md, packages/core/src/lib/Form/Form.stories.tsx, packages/core/src/lib/Form/Form.tsx, packages/core/src/lib/Form/types.ts
---
---
Related issue: [#830](https://github.com/web3ui/web3uikit/issues/830)
Added the Upload component to the Form component (the upload component wasn't changed).
=> added upload component to the form component

.changeset/khaki-suns-fly.md, packages/core/src/lib/Slider/Slider.stories.tsx, packages/core/src/lib/Slider/Slider.styles.ts, packages/core/src/lib/Slider/Slider.test.tsx, packages/core/src/lib/Slider/Slider.tsx, packages/core/src/lib/Slider/types.ts
=> [Slider]: background styles fix

README.md, packages/web3/README.md, packages/web3/src/lib/BlockNumber/BlockNumber.stories.tsx, packages/web3/src/lib/Blockie/Blockie.stories.tsx, packages/web3/src/lib/ConnectButton/ConnectButton.stories.tsx, packages/web3/src/lib/ENSAvatar/ENSAvatar.stories.tsx, packages/web3/src/lib/IPFSInput/IPFSInput.stories.tsx, packages/web3/src/lib/NFT/NFT.stories.tsx, packages/web3/src/lib/NFTBalance/NFTBalance.stories.tsx, packages/web3/src/lib/NativeBalance/NativeBalance.stories.tsx, packages/web3/src/lib/SendTransaction/SendTransaction.stories.tsx, packages/web3/src/lib/WalletModal/WalletModal.stories.tsx, plopfile.js
---
---
rename Moralis web3 to web3parse and change related links in readme 
Related issue: #812
renamed Moralis web3 to web3parse in all related components of section 1 and change related links in readme
=> rename Moralis v1 web3

.changeset/unlucky-brooms-think.md, packages/styles/src/lib/colors.ts
---
---
Minor fix in styles/color
=> remove duplication

packages/core/src/lib/Avatar/types.ts
overide -> override
---
name: 'chore; fix typo in types.ts'
about: fixed typo.
---
=> chore; fix typo in types.ts

.changeset/cold-planets-report.md, packages/core/src/lib/Button/ButtonBase/styles/ButtonBaseTest.styles.tsx
---
---
Minor fix: Remove padding for the Button of theme text.
=> add padding 0 to theme text button

.changeset/khaki-cherries-visit.md, packages/core/src/lib/Checkbox/Checkbox.stories.tsx, packages/core/src/lib/Checkbox/Checkbox.styles.ts, packages/core/src/lib/Checkbox/Checkbox.tsx, packages/core/src/lib/Checkbox/types.ts, packages/core/src/lib/Slider/Slider.styles.ts
---
---
- Fix checkbox theme='box' position to center
- show box when label length =0  i.e label=""
=> [Checkbox]: checkbox styles fix

packages/core/src/lib/Button/types.ts, packages/core/src/lib/Card/Card.tsx, packages/core/src/lib/Card/types.ts, packages/core/src/lib/Typography/types.ts
---
---
Related issue: [#851](https://github.com/web3ui/web3uikit/issues/851)
Added `style` prop to:
- **Card** component,
- **Button** component,
- and **Typography**.
=> Added style prop

.changeset/shaggy-eyes-travel.md, packages/core/src/lib/Grid/Grid.stories.tsx, packages/core/src/lib/Grid/Grid.styles.ts, packages/core/src/lib/Grid/Grid.test.tsx, packages/core/src/lib/Grid/Grid.tsx, packages/core/src/lib/Grid/index.tsx, packages/core/src/lib/Grid/types.ts, packages/core/src/lib/index.ts
---
---
Basic grid element with minimal features for now.
=> [Grid]: New Responsive Grid element

.changeset/cold-peas-complain.md, packages/core/src/lib/PlanCard/PlanCard.styles.tsx, packages/core/src/lib/PlanCard/PlanCard.tsx, packages/core/src/lib/PlanCard/types.ts
=> fix to isActive prop in style

packages/core/src/lib/Typography/Typography.stories.tsx, packages/core/src/lib/Typography/Typography.styles.ts, packages/core/src/lib/Typography/Typography.test.tsx, packages/core/src/lib/Typography/types.ts
---
name: 'Custom Font Size For Typography'
---
Add a custom prop for font size inside the Typography components to avoid overriding styles.
=> feat: Custom Font Size For Typography Coonent

.changeset/angry-forks-retire.md
---
name: 'New Minor release for typography prop'
---
=> Chore: minor release

.changeset/wicked-glasses-sparkle.md, packages/core/src/lib/Illustrations/images/chains/ethereum.tsx, packages/core/src/lib/NftCard/NftCard.stories.tsx, packages/core/src/lib/NftCard/NftCard.styles.ts, packages/core/src/lib/NftCard/NftCard.test.tsx, packages/core/src/lib/NftCard/NftCard.tsx, packages/core/src/lib/NftCard/index.tsx, packages/core/src/lib/NftCard/types.ts, packages/core/src/lib/Select/Select.stories.tsx, packages/core/src/lib/Select/SelectBeta/SelectBeta.styles.ts, packages/core/src/lib/index.ts, packages/core/src/utils/utils.tsx
=> chore: Add NFT UI card

.changeset/angry-forks-retire.md
=> fix: release

.changeset/blue-peas-pump.md, packages/core/src/lib/PlanCard/PlanCard.stories.tsx, packages/core/src/lib/PlanCard/PlanCard.styles.tsx, packages/core/src/lib/PlanCard/PlanCard.tsx, packages/core/src/lib/PlanCard/types.ts
---
---
Add custom props for the scrollbar to avoid CSS hacks on Admin.
=> add custom props for scrollbar

.changeset/slow-trees-deliver.md, packages/core/src/lib/Accordion/Accordion.stories.tsx, packages/core/src/lib/Accordion/Accordion.styles.ts, packages/core/src/lib/Accordion/Accordion.tsx, packages/core/src/lib/Accordion/types.ts, packages/core/src/lib/PopoverDropdown/PopoverDropdown.styles.tsx, packages/core/src/lib/PopoverDropdown/PopoverDropdown.tsx, packages/core/src/lib/PopoverDropdown/types.ts, packages/core/src/lib/Table/Table.stories.tsx, packages/core/src/lib/Table/Table.styles.ts, packages/core/src/lib/Table/Table.tsx, packages/core/src/lib/Table/types.tsx
=> [Accordion]: add custom title and subtitle support

.changeset/big-pens-relax.md, .storybook/preview.js, packages/core/src/lib/Button/Button.stories.tsx, packages/core/src/lib/Button/Button.tsx, packages/core/src/lib/Button/ButtonMoneyPrimary/ButtonMoneyPrimary.styles.tsx, packages/core/src/lib/Button/ButtonMoneyPrimary/ButtonMoneyPrimary.tsx, packages/core/src/lib/Button/types.ts, packages/styles/src/lib/colors.ts
=> 930 button mm style

.changeset/plenty-penguins-smash.md, packages/core/src/lib/Card/Card.stories.tsx, packages/core/src/lib/Card/Card.tsx, packages/core/src/lib/Card/types.ts
---
---
Need this styling in admin
=> [Card]: add tooltip position prop

.changeset/mean-seas-hear.md, packages/core/src/lib/Illustrations/Illustration.tsx, packages/core/src/lib/Modal/Modal.tsx, packages/core/src/lib/Select/OldSelect/OldSelect.tsx, packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx, packages/core/src/lib/TextArea/TextArea.tsx
removing date now ID, tests all pass, i can not remember why i thought this was a good idea
=> fix(Illustration, Modal, Selects, TextArea): remove dateNow error

.changeset/polite-pets-swim.md, packages/core/src/interfaces/customize.ts, packages/core/src/lib/Button/Button.stories.tsx, packages/core/src/lib/Button/ButtonCustom/ButtonCustom.styles.tsx, packages/core/src/lib/Credentials/Credentials.styles.tsx, packages/core/src/lib/Credentials/Credentials.tsx, packages/core/src/lib/InputNew/Input.stories.tsx, packages/core/src/lib/InputNew/Input.styles.ts, packages/core/src/lib/InputNew/Input.tsx, packages/core/src/lib/InputNew/atoms/LabelBase.tsx, packages/core/src/lib/InputNew/atoms/types.ts, packages/core/src/lib/InputNew/types.ts, packages/styles/src/lib/colors.ts
extended TCustomize props and added it to InputNew
=> Fix updates needed for new project

.changeset/calm-crabs-smell.md, packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
Select with traditional mode was not using the placeholder
=> fix(Select): traditional placeholder prop used

.changeset/calm-crabs-smell.md, .changeset/eighty-papayas-look.md, packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
Select Traditional Select now uses placeholder as default option too
=> Fix select tradition placeholder

.changeset/seven-yaks-yell.md, packages/core/src/lib/Avatar/Avatar.stories.tsx, packages/core/src/lib/Avatar/Avatar.tsx, packages/core/src/lib/Avatar/types.ts
you can set the amount of characters to show in the Avatar
=> Fix avatar 3 letter

.changeset/eight-steaks-appear.md, packages/core/src/lib/Skeleton/Skeleton.stories.tsx, packages/core/src/lib/Skeleton/Skeleton.styles.ts, packages/core/src/lib/Skeleton/Skeleton.tsx, packages/core/src/lib/Skeleton/types.ts
- added bg color prop
- added animation color prop
- updated the animation to make it more clear and customisable
=> feat(Skeleton): custom bg colors / updated animation

.changeset/rich-crabs-nail.md, packages/core/src/lib/Hero/Hero.stories.tsx, packages/core/src/lib/Hero/Hero.styles.ts, packages/core/src/lib/Hero/Hero.tsx, packages/core/src/lib/Hero/types.ts
---
---
Fixed same text color for all component issue.
Added customize prop as well.
=> [Hero]: text color and customize prop added

.changeset/itchy-horses-warn.md, packages/styles/src/lib/colors.ts
=> Add new color

.changeset/stale-dryers-sit.md, packages/core/src/lib/InputNew/atoms/styles.ts
small CSS bug fixed @AbhinavMV
=> fix(inputNew): autofill wont change text color

.changeset/cool-carrots-guess.md, packages/core/src/lib/Select/SelectBeta/components/SelectMenuList.tsx
=> [select]: scroll feature remove

.changeset/rich-kiwis-push.md, packages/core/src/lib/Tag/Tag.tsx, packages/core/src/lib/Tag/styles/themes.tsx
=> fix icon sizing , Border box issue

.changeset/tall-grapes-hide.md, packages/core/src/lib/Select/Select.stories.tsx, packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
- no use state
- no use effect
- value can be passed to render default
- index can be passed to render default
- placeholder can be passed to render default
- if nothing is passed 'Please choose' is default so no breaking change
=> fix(Select): default value, index, placeholder and fallback

.changeset/purple-pumpkins-refuse.md, packages/core/src/lib/Info/Information.tsx
---
---
Information component name incorrectly displayed on Storybook
Changed the component name from `<Info/>` to `<Information/>`
=> fix: change name of Information component

.changeset/unlucky-hotels-boil.md, packages/core/src/lib/Select/SelectBeta/SelectBeta.styles.ts, packages/core/src/lib/Select/SelectBeta/SelectBeta.tsx, packages/core/src/lib/Select/SelectBeta/components/SelectMenuList.tsx, packages/core/src/lib/Stepper/helpers/StepperNumbers.styles.ts, packages/core/src/lib/Stepper/helpers/StepperNumbers.tsx
---
---
default index and margin bug fix
=> [SelectBeta]: default index and margin error

.changeset/strange-bags-carry.md, packages/core/src/lib/Tag/Tag.tsx, packages/core/src/lib/Tag/types.ts
Add prexif on tag so we can make icons like this
=> Simple mr adding prefix icon for the tag component

packages/core/src/lib/Input/Input.styles.ts, packages/core/src/lib/InputNew/Input.tsx, packages/core/src/lib/InputNew/atoms/InputBase.tsx, packages/core/src/lib/InputNew/atoms/types.ts, packages/core/src/lib/Select/Select.stories.tsx, packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
- Select HTML5 controlled by state meaning if the value prop changes the value inside it is updated
- Input New controlled by state meaning if the value prop changes the value inside it is updated
- minor style fixes for input and select in confirm and error state when working with input_filled className
=> Select HTML5 & InputNew fixes

README.md
---
name: Discord Link
about: Updated discord link in ReadMe
---
Broken link to Moralis Discord server
Related issue: #1079 
Updated the link to with appropriate one.
=> chore: discord link update

.changeset/sweet-trainers-lay.md, packages/styles/src/lib/breakpoints.ts
new breakpoints for big Chat monitors
=> feat(styles): new very large breakpoints added

.changeset/tall-comics-sniff.md, packages/core/package.json, packages/icons/package.json, packages/nextJs/package.json, packages/styles/package.json, packages/web3/package.json, packages/web3uikit/package.json, pnpm-lock.yaml
Updated exports in package.json to add better ompatibility
=> updated exports in package.json o nevwer format
