web3ui/web3uikit

- src/components/Dropdown/Dropdown.stories.tsx
- src/components/Dropdown/Dropdown.styles.tsx
- src/components/Dropdown/Dropdown.test.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/index.tsx
- src/components/Dropdown/types.ts
- src/components/DropdownElement/DropdownElement.stories.tsx
- src/components/DropdownElement/DropdownElement.styles.tsx
- src/components/DropdownElement/DropdownElement.test.tsx
- src/components/DropdownElement/DropdownElement.tsx
- src/components/DropdownElement/index.tsx
- src/components/DropdownElement/types.ts
- src/index.ts
This is the component that can/should be used to use when creating a dropdown menu.
The only goal of this component is to be 100% customisable, it also allows to set `onClick` event to run a function when clicked.
Height and width are auto if not specified.
Text, icon, colours, size, everything customisable.
> feat: add dropdown element component

- src/components/Dropdown/Dropdown.styles.tsx
- src/components/Dropdown/Dropdown.tsx
- src/components/Dropdown/types.ts
just fixing some markup and having a tinker
> fix(Dropdown): markup alignment

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.styles.ts
- src/components/Modal/Modal.test.tsx
- src/components/Modal/Modal.tsx
- src/components/Modal/types.ts
Added:
- `position: fixed` for displaying the Modal component correctly (see bug bellow)
- background blur for better UX
- interactive Modal Story
Changes:
- Instead of using the Stories for testing I've used `<Modal />` component because we cannot use Storybook preview hooks (`useArgs()`) outside `<Story>`. I've provided all `args` directly to the component
bug:
> upd: Modal

- src/components/Button/Button.tsx
- src/components/Button/types.ts
- src/components/Form/types.ts
- src/components/LinkTo/LinkTo.tsx
- src/components/LinkTo/types.ts
- LinkTo is external type by default
- Button onClick is now optional with `e.preventDeafult()` is default
- Form now takes buttonConfig as optional prop
> Fix link to button optional defaults

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.styles.ts
- src/components/Modal/Modal.tsx
- src/components/Modal/types.ts
- hasCancel optional boolean added, default true, so cancel button can be hidden, CSS fix so ok is always aligned right even without a sibling
- remove all state React code, it should not govern its own state
- added onCancelButtonPress event so the next dev can flip isVisable or better yet unrender the Modal (docs added)
- minor alignment
> fix(Modal): hasCancel boolean added, onCancelButtonPress event added

- .eslintrc.js
Fix for eslint error when working on windows. Without this rule code for people on windows looks like this:
Since we have people working on different OS and code editors I think we should use this rule.
https://eslint.org/docs/rules/linebreak-style#windows
> linebreak-style .eslintrc.js

- src/decorators.tsx
For correct work of all web3 components inside StoryBook stories and having the same Moralis context, we need to use additional web3 connection enabling.
> fixed: decorator for web3 components

- package.json
should make `size.yml` workflow pass
> chore: exclude `crypto` from browser bundle

- src/components/BannerStrip/BannerStrip.test.tsx
- src/components/Button/Button.test.tsx
- src/components/Card/Card.stories.tsx
- src/components/Card/Card.styles.ts
- src/components/Card/Card.tsx
- src/components/Card/types.ts
- src/components/CreditCard/CreditCard.styles.ts
- src/components/CreditCard/CreditCard.tsx
- src/components/CreditCard/types.ts
- src/components/CryptoCards/CryptoCards.test.tsx
- src/components/Icon/Icon.tsx
- src/components/Icon/collection.tsx
- src/components/Icon/types.ts
- src/components/Input/Input.test.tsx
- src/components/LinkTo/LinkTo.test.tsx
- src/components/NewComp/NewComp.test.tsx
- src/components/Notification/Notification.test.tsx
- src/components/Tag/Tag.test.tsx
- src/utils/rgbToHex.ts
I know we can use Button iconOnly to have clickable icons but how should the average user know.
So adding onClick to Icon seems a no-brainer to me
Also:
added CreditCard onPressed method plus added delete Icon again because somehow somebody removed it (:
> feat onClick as Icon prop

- src/components/CopyButton/CopyButton.stories.tsx
- src/components/CopyButton/CopyButton.tsx
- src/components/CopyButton/types.ts
Added revertIn prop to `CopyButton`. <br>
It accepts a number in `ms` that is used to revert the `CopyButton` image to default after `revertIn` ms.
Usage (6.5 seconds):
```js
<CopyButton
text="With Love from Developers"
revertIn={6500}
onCopy={() =>
notify({
type: 'success',
message: 'Copied to clipboard',
title: 'New Notification',
position: 'topR',
})
}
/>
```
> feat: Revert prop added to Copy Button

- src/components/Icon/Icon.styles.tsx
Giving a max width and height, so if a user just has one icon, by default it would span the whole, page. We don't want that 😅
> feat: just thinking ahead of possible ways this could have bad ux

- src/components/Typography/Typography.tsx
- src/components/Typography/types.ts
fix for the issue when you pass children text:
> fix(Typography): strict types removed

- src/components/Checkbox/Checkbox.test.tsx
- src/components/Checkbox/Checkbox.tsx
Since CheckBox has its own state `isChecked` we need to also listen to changes in the `checked` prop and update state.
BUG demo:
> feat(CheckBox): added useeffect for upd state from prop

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.styles.ts
- src/components/Modal/Modal.tsx
- src/components/Modal/types.ts
Modal now accept a custom close button!
```js
CustomCloseRoundButton.args = {
id: 'regular',
title: 'Confirm',
isVisible: true,
closeButton: (
<Button
icon="arrowCircleRight"
iconLayout="icon-only"
id="test-button-primary-icon-only"
onClick={() => {}}
text="Primary icon only"
theme="primary"
type="button"
radius={40}
/>
),
children: [
<div
key={'0'}
style={{
display: 'flex',
alignItems: 'center',
justifyContent: 'center',
flexDirection: 'column',
}}
>
<Icon svg={iconTypes.cloud} size={64} fill={colors.blueDark2} />
<p>Proceed uploading?</p>
</div>,
],
};
```
> feat: custom close button for modal component

- src/components/BannerStrip/BannerStrip.styles.ts
- src/components/BannerStrip/BannerStrip.tsx
Things done: closes #237 
- Removed padding top and bottom from button
- Added small margin to the button
- Removed border from button since it was not looking with it when button is large (let me know if this needs to reverted)
- Removed unused styles from the file
Ran the BannerStrip test file after these changes and all tests passed.
> BannerStrip: Add margin and remove padding from button

- src/components/Input/Input.tsx
The `<Input>` component hides type "password" by default.
> fix: Input component hide type <password> by default

- src/components/Modal/Modal.styles.ts
> feat: hide vertical scrollbar

- src/components/Modal/Modal.styles.ts
- src/components/Modal/Modal.tsx
- src/components/Modal/types.ts
closes #223 
Made header and footer sticky (also added same style for custom footer)
Since style are added on header and footer elements itself so don't need to take care of no header and footer scenario.
Let me know if anything needs to be changed 
https://user-images.githubusercontent.com/35369843/159119796-8feb0f3b-8fc9-4332-98ec-a1c5d2f49467.mp4
> [bug]: Fix Modal Header and Footer

- src/components/Button/Button.stories.tsx
- src/components/Button/Button.styles.ts
- src/components/Button/styles/inititalStyles.ts
Added back the `transparent` button. Used to remove background to any `secondary` type button. <br>
This does simulate an icon, but with onclick property
> feat: transparent button

- src/components/Card/Card.stories.tsx
- src/components/Card/types.ts
The `Card` component now accepts JSX Element as `tooltipText`. This allows to set a custom width to the text and uses the `Tooltip` functionality fully.
> fix: tooltipText prop in Card component now accepts JSX.Element as well

- src/components/Checkbox/Checkbox.tsx
closes #326 
Fixed by passing defaultChecked attribute to input element
> Fix checkbox 2 clicks

- src/components/Modal/Modal.tsx
This PR fixes a memory leak bug related to the `onclick` listener enabled in `useEffect`.
```js
document.addEventListener('click', handleContentClick);
```
> fix: remove event listeners when component unmounts

- src/components/Credentials/Credentials.stories.tsx
- src/components/Credentials/Credentials.tsx
- src/components/Credentials/components/CredentialsHeader.tsx
- src/components/Credentials/types.ts
Added text color customization for `Credentials`
> feat(Credentials): added text color customization

- src/components/BannerStrip/BannerStrip.styles.ts
- src/components/BannerStrip/BannerStrip.test.tsx
- src/components/BannerStrip/BannerStrip.tsx
closes #359 
I have some doubts here.
1. stories file also uses named export. Does that also needs to be scoped?
2. In the section styles, z-index: 1001 is used. But what if we have a navbar and a bannerstrip on the page and user tries to scroll on that page.
In this case the bannerstrip would end up getting on top of navbar. 
Let me know if my understanding is correct or am i missing something. Thanks.
> React18 refactor banner strip and styles

- src/components/Breadcrumbs/Breadcrumbs.styles.ts
- src/components/Breadcrumbs/Breadcrumbs.test.tsx
- src/components/Breadcrumbs/Breadcrumbs.tsx
- src/components/Breadcrumbs/types.ts
- scoped CSS without named exports (except one)
closes #360
> React18 refactor breadcrumbs

- src/components/Icon/Icon.styles.tsx
- src/components/Icon/Icon.test.tsx
- src/components/Icon/Icon.tsx
- src/components/Icon/icons/ada.tsx
- src/components/Icon/icons/atomicApi.tsx
- src/components/Icon/icons/avax.tsx
- src/components/Icon/icons/bnb.tsx
- src/components/Icon/icons/btc.tsx
- src/components/Icon/icons/chainlink.tsx
- src/components/Icon/icons/dapps.tsx
- src/components/Icon/icons/doge.tsx
- src/components/Icon/icons/eth.tsx
- src/components/Icon/icons/fil.tsx
- src/components/Icon/icons/matic.tsx
- src/components/Icon/icons/metamask.tsx
- src/components/Icon/icons/metamaskLined.tsx
- src/components/Icon/icons/oneinch.tsx
- src/components/Icon/icons/shib.tsx
- src/components/Icon/icons/speedyNode.tsx
- src/components/Icon/icons/uni.tsx
- src/components/Icon/icons/usdc.tsx
- src/components/Icon/icons/usdt.tsx
- src/components/Icon/icons/web3api.tsx
- src/components/Icon/icons/xrp.tsx
- added data-testid and aria-hidden attributes to many of the svg's.
closes #369
> React18 refactor Icon

- src/components/TextArea/TextArea.styles.ts
- src/components/TextArea/TextArea.tsx
- src/components/TextArea/types.tsx
Fixed issue on mozilla.
closes #457 
Removed type prop as it is unused. Let me know if this needs to be reverted.
> [Fix] Text Area - Placeholder visible behind label

- src/components/CodeArea/CodeArea.tsx
- src/components/CodeArea/types.ts
Standard HTML prop for `textarea` we use in the `<CodeArea />`
closes #474
> feat(CodeArea): added disabled prop

- src/components/Credentials/Credentials.stories.tsx
- src/components/Credentials/Credentials.styles.tsx
- src/components/Credentials/Credentials.tsx
- src/components/Credentials/components/TruncateString.tsx
- src/components/Credentials/types.ts
Things done:
- Fixed the overflow error.
- Truncate text on smaller screen
- Made this truncate text component as reusable as possible - (Let me know if it needs to be moved to a different folder)  
closes #454
> Fix:Credentials comp - Mobile screen text truncate

- src/components/Select/Select.stories.tsx
- src/components/Select/Select.styles.ts
> fix: Select use same padding as SelectedOption for Option

- src/components/ChainSelector/ChainSelector.tsx
- src/components/Table/Table.styles.ts
- src/components/Tabs/Tabs.styles.ts
Closes #530 
Table scrolling in mobile view instead of screen overflow. 
scrollbar is hidden - since in mobile view user uses touch input to scroll instead of scrollbar
closes #529 
if IsMultipleAllowed is false then only single item can be selected (For admin syncs user wallet)
closes #523
> Table overflow and Chain Selector

- src/components/Select/Select.stories.tsx
- src/components/Select/Select.styles.ts
- src/components/Select/Select.tsx
- src/components/Select/types.ts
Description below select component. for both Traditional HTML5 and default. 
For default if state=error and errorMessage is present error message would be shown else description message.
closes #549
> feat: description for select comp

- src/components/Modal/Modal.stories.tsx
- src/components/Modal/Modal.styles.ts
- src/components/Modal/Modal.tsx
- src/components/Modal/types.ts
Fix #510 
- Fixed the vertical scrolling for big content modal so it scrolls outside the modal not inside
https://user-images.githubusercontent.com/13832392/166104665-5d7b6dd1-d8b5-4f7d-9c87-8892e00831b1.mp4
- I realized that there are some modals that are not vertical centered and others with vertical center like this modal
So I added `isCentered` props to center the modal vertically on demand
> Fix modal v scroll

- src/components/Credentials/Credentials.tsx
@BillyG83 I changed the color for the hidden text to what we've in the design
> fixed credentials styles

- src/components/Typography/Typography.stories.tsx
- src/components/Typography/Typography.styles.ts
- src/components/Typography/types.ts
---
name: 'Typography supports custom font-weights'
---
Poor `fontWeight` support in Typography.
Now the Typography supports weight 550. Also Typography now supports all string type weights , but only standard weights will be displayed in  the hints.
> feat(Typography): 550+custom weights support added

- src/components/Input/Input.styles.ts
- src/components/Input/Input.tsx
---
name: 'Input '
about: Input Component filled
---
Related issue: #586 
Fix styling for input component
Bug fixed as well in which, after `validation error` of comp is fixed then state changes to `confirmed` and after 3 sec state changes to `initial`. This was changing the label styles as well.
> [Input]: fix styling for filled input

- src/components/PopoverDropdown/PopoverDropdown.stories.tsx
- src/components/PopoverDropdown/PopoverDropdown.styles.tsx
---
about: Popover Dropdown
---
Related issue: #716 
Instead of the tooltip, we can display a popover dropdown inside a popover dropdown. This is because Tooltip is usually used to display information. But in admin panel we need to switch teams from the popover dropdown. 
Let me know if this has an issue 🙌🏻
> Popover Dropdown inside Dropdown

- src/components/NFT/NFT.fetched.tsx
- src/components/NFT/NFT.tsx
- src/components/NFT/NFT.utils.tsx
- src/components/NFT/types.ts
---
---
Related issue: #717 
- removed hardcode value = `ERC721`. Now user can pass the contract type (This is only used when no metadata is fetched by the api).
- fixed issue, video link starting with `ipfs://.....` where not being converted to `https:/...`
> fix(NFT): Add contract type prop and manipulate video link

- packages/core/src/lib/Upload/Upload.tsx
---
name: 'fix-upload.tsx-component'
about: previously component triggered onChange function immediately after the render, it should call onChange when something is changed. 
---
> onChange function  shouldn't call when component render

- packages/core/src/lib/DatePicker/DatePicker.stories.tsx
---
---
In Datepicker component in Static Date story inside Forms section, when the type is set to month, it doesn't works instead shows blank line. 
Related issue: #836
when type is set to date then format for default/static value is 'yyyy-mm-dd' 
when the type is set to month static value format should be 'yyyy-mm'.
I created a new story for the case of type-month with 'yyyy-mm' as a static value to let the users know that both static date format is different for type month.
> added story for static month in DatePicker

- .changeset/clever-jeans-act.md
- packages/core/src/lib/Upload/Upload.stories.tsx
- packages/core/src/lib/Upload/Upload.tsx
- packages/core/src/lib/Upload/types.ts
---
---
Related issue: [#862](https://github.com/web3ui/web3uikit/issues/862).
Updated Upload component:
- users can select only certain file types to be accepted with `acceptedFiles` prop
- can set custom text with `descriptionText` prop
- using `style` prop they can set custom CSS
- if non-image file is uploaded the component won't break
- the name of the uploaded file is written below the image/icon
Example of non-image file uploaded.
Example of custom text and custom CSS.
> Updated Upload Component

- .changeset/nice-beers-press.md
- packages/core/src/lib/PlanCard/PlanCard.stories.tsx
- packages/core/src/lib/PlanCard/PlanCard.styles.tsx
- packages/core/src/lib/PlanCard/PlanCard.test.tsx
- packages/core/src/lib/PlanCard/PlanCard.tsx
- packages/core/src/lib/PlanCard/mock.tsx
- packages/core/src/lib/PlanCard/types.ts
---
---
related to [issue](https://gabronickwontdiefromcovid.com/moralis/admin-panel-squad/moralis-admin-frontend/-/issues/1051)
* Add horizontalLine prop where it controls the horizontal line on the top. 
* Add borderColor and backgroundColor props So we don't strict to the white background.
* And also Icon prop for the description list 
New Looks
> Add some props to PlanCard

- .changeset/purple-walls-trade.md
- packages/core/src/lib/BannerStrip/BannerStrip.styles.ts
- packages/core/src/lib/BannerStrip/BannerStrip.tsx
- packages/core/src/lib/BannerStrip/types.ts
1. position fixed should not add z-index, top or left... they are not needed
2. sorted CSS and props 🔤 
3. added style prop for margin in admin
> fix(BannerStrip): position relative should not use z-index, top or left

- .changeset/beige-fishes-flash.md
- packages/core/src/lib/Credentials/Credentials.stories.tsx
- packages/core/src/lib/Credentials/Credentials.tsx
- packages/core/src/lib/Credentials/types.ts
---
---
Related issue: #[Admin Issue](https://gabronickwontdiefromcovid.com/moralis/admin-panel-squad/general/-/issues/60)
Add Callbacks
* onCopy
* onReveal
> Add callbacks

- .changeset/new-pets-clean.md
- packages/core/src/interfaces/customize.ts
- packages/core/src/lib/Button/ButtonCustom/ButtonCustom.styles.tsx
- packages/core/src/lib/Button/types.ts
- packages/core/src/lib/CopyButton/CopyButton.tsx
- packages/core/src/lib/CopyButton/types.ts
- packages/core/src/lib/Credentials/Credentials.stories.tsx
- packages/core/src/lib/Credentials/Credentials.styles.tsx
- packages/core/src/lib/Credentials/Credentials.tsx
- packages/core/src/lib/Credentials/types.ts
- packages/core/src/lib/Typography/Typography.tsx
- packages/core/src/lib/Typography/types.ts
> feat(Customize): Credentials and Button

- .changeset/rotten-starfishes-watch.md
- packages/core/src/lib/CopyButton/CopyButton.tsx
- packages/core/src/lib/Credentials/Credentials.stories.tsx
- packages/core/src/lib/Credentials/Credentials.tsx
- packages/core/src/lib/Credentials/components/TruncateString.tsx
- packages/core/src/lib/Credentials/types.ts
- packages/core/src/lib/HideButton/HideButton.tsx
- packages/core/src/lib/index.ts
---
---
When these Hide and copy buttons are used inside a Form they act as submit buttons by default.
These buttons would never be used for submit so solution is to give them `type='button'`
> [Copy,Hide]: Fix button types

- .changeset/angry-onions-shake.md
- packages/core/src/hooks/useOutsideAlerter.ts
- packages/core/src/lib/Dropdown/Dropdown.tsx
closes https://github.com/web3ui/web3uikit/issues/958 <br />
> feat: add useOutsideAlerter hook and fix dropdown

- .changeset/little-boxes-swim.md
- packages/core/src/lib/Credentials/Credentials.stories.tsx
- packages/core/src/lib/Credentials/Credentials.styles.tsx
- packages/core/src/lib/Credentials/Credentials.tsx
- packages/core/src/lib/Credentials/components/CustomCopyButton.tsx
- packages/core/src/lib/Credentials/components/CustomHideButton.tsx
- packages/core/src/lib/Credentials/types.ts
- packages/core/src/lib/Tooltip/Tooltip.stories.tsx
- packages/core/src/lib/Tooltip/Tooltip.styles.ts
- packages/core/src/lib/Tooltip/Tooltip.tsx
- packages/core/src/lib/Tooltip/types.ts
---
---
Tooltip - Added arrow size change prop and customize prop
Credentials - Added prop for showing tooltips on icons
Both changes are linked to each other so doing it in the same PR
> [Credentials,Tooltip]: Added customize prop and tooltips for icon

- .changeset/new-wasps-hear.md
- packages/core/src/lib/Select/Select.stories.tsx
- packages/core/src/lib/Select/Select.test.tsx
- packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
- packages/core/src/lib/Select/types.ts
Render
Open
Redner
Open
Render
Open
> fix(Select): HTML 5 default index & placeholder

- .changeset/lazy-otters-cry.md
- packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
> chore: add prefix for html5 select

- .changeset/wild-apes-decide.md
- packages/core/src/lib/Select/Select.stories.tsx
- packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
- packages/core/src/lib/Select/types.ts
HTML5 select can have disabled options that could be used as titles
> feat(Select): HTML5 takes disabled options

- .changeset/wet-hats-search.md
- packages/web3/src/lib/ConnectButton/types.ts
despite taking all extraneous props passed to `ConnectButton`:
and passing them through to the `WrapperStyled` (which is just a styled.div):
the typings don't actually allow for passing through extraneous properties other than the 3 explicitly defined properties on `IConnectButtonProps`:
indicate that `IConnectButtonProps` extends the native HTML attributes for divs, allowing typescript consumers to know they can safely pass through other props such as `className` :3
> fix: indicate that any div props can be passed through to ConnectButton

- .changeset/slow-jobs-peel.md
- packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
Default (no value)
Value passed as string into value prop
Value being passed as default index
> fix(Select): html respects value passed

- .changeset/hot-snails-tap.md
- packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
reverting to V0.2.47 of the Select HTML5 mode as its the most recent working version. when i have more time i will try to debug why its returning the label and not the id from a standard event, but its happening under the hood of react-form-hook so i need time to take it apart locally.
> 1067 select html5 mode returns unexpected result

- .changeset/dry-monkeys-scream.md
- packages/core/src/lib/Credentials/Credentials.styles.tsx
---
name: 'Fix Credential Component magins'
about: A bug related to the margins of the divider used in the credentials component
---
The divider used to divide icons (hide and copy) in the `Credentials` component is broken. Example: 
Fix the divider margins.
Now:
> Credential: fix icon divider margin

- .changeset/unlucky-years-decide.md
- packages/core/src/lib/Slider/Slider.stories.tsx
- packages/core/src/lib/Slider/Slider.styles.ts
- packages/core/src/lib/Slider/Slider.tsx
- packages/core/src/lib/Slider/types.ts
- added track bgColor prop
- added thumb box-shadow props
- added new story
- texted all other stories
Custom:
Default:
Strepper:
Disabled:
> feat(Slider): track bgColor and thumb box shadow prop added

- .changeset/tall-waves-occur.md
- packages/core/src/lib/ProgressBar/ProgressBar.stories.tsx
- packages/core/src/lib/ProgressBar/ProgressBar.styles.ts
- packages/core/src/lib/ProgressBar/ProgressBar.test.tsx
- packages/core/src/lib/ProgressBar/ProgressBar.tsx
- packages/core/src/lib/ProgressBar/index.tsx
- packages/core/src/lib/ProgressBar/types.ts
- pnpm-lock.yaml
---
name: 'Create new progressBar component'
---
Related issue: [1095](https://github.com/web3ui/web3uikit/issues/1095)
Added a ProgressBar component with the default prop and customized settings.
> 1095 feat progressbar added comp

- .changeset/curvy-emus-begin.md
- packages/core/src/lib/InputNew/Input.tsx
- packages/core/src/lib/Select/TraditionalSelect/TraditionalSelect.tsx
---
name: 'Fix add name select input elements'
about: Adding name to the elements select and input
---
We are currently missing name from the elements select and input, this adds name to the element. 
BEFORE:  
AFTER: 
BEFORE:  
AFTER:
> Fix add name select input elements

- packages/core/src/lib/Toggle/Toggle.tsx
- packages/core/src/lib/Toggle/types.ts
Added `isChecked` prop to Toggle to define whether the toggle state is `on` or `off`. <br />
It counters the toggle state to reset and make sure it is always set correctly.
> Add prop isChecked to Toggle component
